# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agoraDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgoraDialog(object):
    def setupUi(self, AgoraDialog):
        AgoraDialog.setObjectName("AgoraDialog")
        AgoraDialog.resize(854, 324)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AgoraDialog.sizePolicy().hasHeightForWidth())
        AgoraDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("agoraIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AgoraDialog.setWindowIcon(icon)
        AgoraDialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(AgoraDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataTable = QtWidgets.QTableWidget(AgoraDialog)
        self.dataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dataTable.setWordWrap(False)
        self.dataTable.setRowCount(0)
        self.dataTable.setColumnCount(5)
        self.dataTable.setObjectName("dataTable")
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(4, item)
        self.dataTable.horizontalHeader().setVisible(True)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.dataTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.dataTable)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkAllButton = QtWidgets.QPushButton(AgoraDialog)
        self.checkAllButton.setObjectName("checkAllButton")
        self.horizontalLayout_2.addWidget(self.checkAllButton)
        self.uncheckAllButton = QtWidgets.QPushButton(AgoraDialog)
        self.uncheckAllButton.setObjectName("uncheckAllButton")
        self.horizontalLayout_2.addWidget(self.uncheckAllButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.clearStatusButton = QtWidgets.QPushButton(AgoraDialog)
        self.clearStatusButton.setObjectName("clearStatusButton")
        self.horizontalLayout_2.addWidget(self.clearStatusButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refreshButton = QtWidgets.QPushButton(AgoraDialog)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.retrieveButton = QtWidgets.QPushButton(AgoraDialog)
        self.retrieveButton.setObjectName("retrieveButton")
        self.horizontalLayout.addWidget(self.retrieveButton)
        self.transferButton = QtWidgets.QPushButton(AgoraDialog)
        self.transferButton.setObjectName("transferButton")
        self.horizontalLayout.addWidget(self.transferButton)
        self.ignoreButton = QtWidgets.QPushButton(AgoraDialog)
        self.ignoreButton.setObjectName("ignoreButton")
        self.horizontalLayout.addWidget(self.ignoreButton)
        self.statusLabel = QtWidgets.QLabel(AgoraDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        self.quitButton = QtWidgets.QPushButton(AgoraDialog)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(AgoraDialog)
        QtCore.QMetaObject.connectSlotsByName(AgoraDialog)

    def retranslateUi(self, AgoraDialog):
        _translate = QtCore.QCoreApplication.translate
        AgoraDialog.setWindowTitle(_translate("AgoraDialog", "Agora Siemens UI"))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("AgoraDialog", "Transfer"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("AgoraDialog", "MeasID"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("AgoraDialog", "ProtName"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("AgoraDialog", "PatName"))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("AgoraDialog", "Target"))
        self.checkAllButton.setText(_translate("AgoraDialog", "Check All"))
        self.uncheckAllButton.setText(_translate("AgoraDialog", "Uncheck All"))
        self.clearStatusButton.setText(_translate("AgoraDialog", "Clear Status"))
        self.refreshButton.setToolTip(_translate("AgoraDialog", "<html><head/><body><p>Refresh the data list</p></body></html>"))
        self.refreshButton.setText(_translate("AgoraDialog", "Refresh"))
        self.retrieveButton.setToolTip(_translate("AgoraDialog", "<html><head/><body><p>Copy the data to the local drive</p></body></html>"))
        self.retrieveButton.setText(_translate("AgoraDialog", "Retrieve"))
        self.transferButton.setToolTip(_translate("AgoraDialog", "<html><head/><body><p>Transfer the data to Agora</p></body></html>"))
        self.transferButton.setText(_translate("AgoraDialog", "Transfer"))
        self.ignoreButton.setText(_translate("AgoraDialog", "Ignore"))
        self.statusLabel.setText(_translate("AgoraDialog", "Status: Idle"))
        self.quitButton.setText(_translate("AgoraDialog", "Quit"))
